FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    SHARED_VOLUME_PATH=/data/shared

WORKDIR /app

COPY app_data_eng.py ./

RUN pip install --no-cache-dir pandas

EXPOSE 8080

CMD ["python", "app_data_eng.py"]
